import mongoose from "mongoose";
const Schema = mongoose.Schema;
const ObjectId = mongoose.Types.ObjectId;

/* const CaseSchema = new Schema({
  name: String,
  photoId: Boolean,
  photosTaken: Boolean,
  independentContractNumber: String,
  accidentDateTime: Date,
  email: String,
  dateOfBirth: String,
  w7: String,
  nameOfReferrer: String,
  homePhoneNumber: String,
  streetAddress: String,
  city: String,
  county: String,
  state: String,
  zip: String,
  emergencyContactName: String,
  emergencyContactRelationship: String,
  emergencyContactPhoneNumber: String,
  maritalStatus: Number,
  spouseName: String,
  spouseOccupation: String,
  language: String,
  countryOfOrigin: String,
  immigrationStatus: Number,
  dateOfArrivalInUs: Date,
  translatorRequired: Boolean,
  education: Number,
  height: String,
  weight: Number,
  race: String,
  rightOrLeftHanded: Number,
  sex: Number,
  medicaidOrMedicare: String,
  privateInsurance: String,
  isPreviousCustomer: Boolean,
  criminalHistory: String,
  owesChildSupport: Boolean,
  injuryHistory: String,
  workmansCompHistory: String,
  accidentBodyParts: String,
  accidentLocation: String,
  accidentDetails: String,
  accidentOthersAtFault: String,
  employerName: String,
  employerPhoneNumber: String,
  employerAddress: String,
  injuredJobTitle: String,
  departmentOfHealth: String,
  payRate: Number,
  hoursPerWeek: Number,
  occHistory: String,
  cashOrCheck: Number,
  taxesWithheld: Boolean,
  estimatedAverageWeeklyWage: Number,
  estCr: String,
  thirdPartyAtFault: Boolean,
  numberOfInjuredEmployees: Number,
  concurrentEmployment: String,
  witnesses: String,
  disabilityStatus: Number,
  shortTermLongTermDisablity: Boolean,
  chiropractor: Boolean,
  notificationDate: Date,
  employerIncidentNotifier: String,
  supervisor: String,
  generalContractInformation: String,
  carrierName: String,
  carrierAddress: String,
  carrierPhoneNumber: String,
  adjusterName: String,
  claimNumber: Number,
  policyNumber: Number,
  opposingFirmName: String,
  opposingAttorneyName: String,
  opposingAddress: String,
  opposingPriorAttorney: String,
  providers: String,
  pointsOfContact: String,
}); */
const CaseSchema = new Schema({
  name: String,
  photoId: Boolean,
  photosTaken: Boolean,
});

const CaseModel = mongoose.model("Case", CaseSchema);

export default CaseModel;
